### PR TITLE
Fix compilation errors from implicit typecasts

### PR DESCRIPTION
**Pull request by 4e554c4c**
Supersedes #133, #135

### CODE REVIEW

**Comment by cmuellner** [comment]
Thanks for the fix!
It would be great to see this in a release.

**Comment by 4e554c4c** [comment]
> Thanks for the fix! It would be great to see this in a release.

indeed. see #137

**Comment by cmuellner** [comment]
Thank you very much for moving this forward!

**Comment by jwright6323** [comment]
Thanks!

**Pull request merged**
