### PR TITLE
Update version.rb to trigger new release/gem

### PR DESCRIPTION
**Pull request by jhongturney**
I believe this change triggers the Actions workflow to create the new tag and gem for 1.6.15

### CODE REVIEW

**Comment by jhongturney** [comment]
@gjtorikian Hello again - I think this is the final step in getting the trim bump into a mathematical release/gem (sorry I didn't catch it with the previous PR).  I don't think the tests will pass, but I don't think they matter in this case.  Once this merges, it looks like the Tag/Release Action will kick off, unless I'm mistaken.  Please let me know if there's anything else I can do 🙇🏻

**Comment by gjtorikian** [comment]
I myself am not even sure if the action works, I largely don't maintain this repo 😓  But let's find out

**Comment by gjtorikian** [comment]
I messed up the release, but this is out as 1.6.16 now.

**Comment by jhongturney** [comment]
@gjtorikian I didn't realize at first, but there's something still wrong with the gem file.  The 1.6.16 build is only registering as `19K`, whereas 1.6.13 was `26M`... and which explains why it won't properly install/build 😅 

Can you try again? 🙏🏻

**Comment by gjtorikian** [comment]
Guh, I received a local compilation error. I haven't got time to dig in right now, but I will try to do so later today.

**Comment by jhongturney** [comment]
Thank you, I appreciate your time and effort!

**Comment by gjtorikian** [comment]
I have bad news on top of bad news.

The C dependencies in this project aren't compiling to do a (new) error with Lasem, specifically, this line: `lsm_dom_view_render`

It also seems like the Lasem project has been archived since Sept 2020. I would, ideally, like to find a new MathML -> SVG/PNG converter, but I don't have the time right now, due to work/life obligations. Sorry for leaving you hanging. I did try to revert back to an older Lasem SHA (79d2b9c0a27a420683634a222a818d4333c85fb7) in case the recent bump broke something, but that, too, did not resolve the problem. 

If I had to guess, one of the underlying dependencies--`cairo`, most likely—was updated in a way I haven't been able to sort out. Sorry to leave this hanging/broken for now.

**Comment by jhongturney** [comment]
Yeah, totally understand... that's the risk in trying to update older things 😄 I really do appreciate your effort here, though!

**Pull request merged**
